version: '3.4'
services:
  nodejs:
    container_name: nodejs
    build: .
    restart: always
    ports:
      - "8080:8080"
    links:
      - "mongo"
    depends_on:
      - "mongo"
  
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27018:27017"
    logging:
      driver: none
